### ISSUE TITLE
no attribute 'packages_server' in pillars

### ISSUE THREAD

**Issue by zecharyah** [pndaproject/platform-salt#203]
Hi,
 
I installed salt-master and salt-minion on two running vagrant machines, got this repository on the salt-master and ran the state.apply

When I apply state I get  `no attribute 'packages_server'` error for many components, and indeed there is no `packages_server` defined in `/srv/pillars/services.sls`. How it's supposed to find this value?

the error is coming from this line : `{% set packages_server = pillar['packages_server']['base_uri'] %}`

Thanks!

**Comment by jgarnier** [comment]
Hi,

You can not provisioned PNDA on 2 Vagrant images, check the provisioning section of the PNDA guide in order to have all the details: https://github.com/pndaproject/pnda-guide/blob/develop/provisioning/OVERVIEW.md
