### ISSUE TITLE
Deployment failed due to saltstack queuing issue

### ISSUE THREAD

**Issue by janselva** [pndaproject/platform-salt#290]
Deployment failed due to saltstack issue.

The function "state.sls" is running as PID 25102 and was started at 2017, Sep 07 11:14:20.814216 with jid 20170907111420814216

**Comment by trsmith2** [comment]
What state was being run at this point? Generally this message indicates a loop/wait without exit in the state code and an attempt to re-run e.g. highstate.

**Comment by janselva** [comment]
Fixed in PR 114, **https://github.com/pndaproject/pnda-heat-templates/pull/114**
