### ISSUE TITLE
HADOOP MAPREDUCE JOB FAILS TO RUN on HDP STANDARD CLUSTER

### ISSUE THREAD

**Issue by MANASASRIRAMENENI** [pndaproject/platform-salt#385]
**Case:**
1. Create a KAFKA topic and produce data to it.
2. Run Gobblin service to collect data from KAFKA topic and create a dataset in HDFS.

**ISSUE**:
1. Gobblin service exits with an error saying "**Exception from Container Launch**" when it tries to run a **HADOOP MAPREDUCE JOB**.
2. Container log shows that "**WEB APP FAILED TO START**". It ignores this error and goes ahead with next set of operation where it tries to "GET_HTTP_PORT" of WEB APP which didn't even start due to an **exception(JAVA NULL POINT EXCEPTION due to STRING JOIN OPERATION**).
3. After going through hadoop codebase, figured out that for WEB APP to start it is trying to access few parameters from **hadoop "yarn-site.xml" configuration file** which are not available in current configuration file.

**PARAMETERS MISSING**:
"yarn.resourcemanager.webapp.address.rm1" : "%(cluster_name)s-hadoop-mgr-1:8088",
"yarn.resourcemanager.webapp.address.rm2" : "%(cluster_name)s-hadoop-mgr-2:8088",
"yarn.resourcemanager.webapp.https.address.rm1" : "%(cluster_name)s-hadoop-mgr-1:8090",
"yarn.resourcemanager.webapp.https.address.rm2" : "%(cluster_name)s-hadoop-mgr-2:8090",

**FIX**:
After adding above parameters in "**yarn-site" section inside "platform-salt/salt/hdp/templates/cfg_standard.py.tpl"** file,  I am able to successfully run HADOOP MAPREDUCE JOBS without any CONTAINER EXCEPTION..

**Comment by trsmith2** [comment]
Does this happen on all standard HDP clusters at 3.6? If not, can you explain the context a little more so we can reproduce it?

**Comment by MANASASRIRAMENENI** [comment]
Hi Trevor,

It happens on both UBUNTU and RHEL HDP STANDARD CLUSTERS

**Comment by MANASASRIRAMENENI** [comment]
After creating KAFKA topic and produce data to it and then run Gobblin service which fails due to "Container launch exception" which occurs when it tries to start a hadoop mapreduce job.

**Comment by MANASASRIRAMENENI** [comment]
[log.txt](https://github.com/pndaproject/platform-salt/files/1558324/log.txt)

**Comment by MANASASRIRAMENENI** [comment]
Please find the attached container log file

**Comment by trsmith2** [comment]
Does this happen on all standard HDP clusters at 3.6?

**Comment by MANASASRIRAMENENI** [comment]
Yes.

**Comment by trsmith2** [comment]
Even AWS clusters?

**Comment by MANASASRIRAMENENI** [comment]
It's on AWS clusters where I faced the above issue.

**Comment by MANASASRIRAMENENI** [comment]
Fix has been merged for above issue(commit: 1f2d42f977a8f02eacd411308517ec496a09aca0)
