### ISSUE TITLE
services.sls lacks livy release version

### ISSUE THREAD

**Issue by lucioseki** [pndaproject/platform-salt#415]
PNDA release/3.6 build-pnda.sh now builds livy, and by default it tries to download corresopnding .tar.gz specified by services.sls:

`    LV_VERSION=$(wget -qO- https://raw.githubusercontent.com/pndaproject/platform-salt/${ARG}/pillar/services.sls | shyaml get-value livy.release_version) `

However, services.sls does not contain livy release_version on tag release/3.6.

So services.sls and release/3.6 tag should be updated.

**Comment by trsmith2** [comment]
We don't build livy in 3.6 (see xhttps://raw.githubusercontent.com/pndaproject/pnda/release/3.6/build/build-pnda.sh)

Probably you cloned the latest version of pnda.git instead of release/3.6.
